name: Verify Refactoring Data

on:
  push:
    paths:
      - "webapp/poly/static/data/mid-school-refactoring.txt"
  pull_request:
    paths:
      - "webapp/poly/static/data/mid-school-refactoring.txt"
  workflow_dispatch: # 수동 실행을 위한 트리거 추가

jobs:
  verify_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sympy

      - name: Run data verification
        run: |
          python webapp/poly/_github_actions/verify_refactoring_data.py webapp/poly/static/data/mid-school-refactoring.txt

      - name: Check results
        if: failure()
        run: |
          echo "Data verification failed. Please check the logs."
